[pytest]
filterwarnings =
    ignore:Using .* with .*starlette.testclient.* is deprecated:Warning
    ignore:The anyio.abc.BlockingPortal alias is deprecated:DeprecationWarning
    ignore:`torch.jit.script` is deprecated:FutureWarning
    ignore:numpy.core is deprecated:DeprecationWarning
    ignore:Call to deprecated function 'Dependency'.*:Warning
    ignore:Use of deprecated class 'DependencyKwarg'.*:Warning
    ignore:invalid value encountered in divide:RuntimeWarning
